/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReparacionesRouteImport } from './routes/_authenticated/reparaciones'
import { Route as AuthenticatedRecomendacionesBloqueoRouteImport } from './routes/_authenticated/recomendaciones-bloqueo'
import { Route as AuthenticatedPreviewRouteImport } from './routes/_authenticated/preview'
import { Route as AuthenticatedPicarOfRouteImport } from './routes/_authenticated/picar-of'
import { Route as AuthenticatedOfFabricadasRouteImport } from './routes/_authenticated/of-fabricadas'
import { Route as AuthenticatedMoldesRouteImport } from './routes/_authenticated/moldes'
import { Route as AuthenticatedIncidenciasProductoRouteImport } from './routes/_authenticated/incidencias-producto'
import { Route as AuthenticatedIncidenciasRouteImport } from './routes/_authenticated/incidencias'
import { Route as AuthenticatedIncidenciaProductoFormRouteImport } from './routes/_authenticated/incidencia-producto-form'
import { Route as AuthenticatedGestionMoldesRouteImport } from './routes/_authenticated/gestion-moldes'
import { Route as AuthenticatedBloquearCanalRouteImport } from './routes/_authenticated/bloquear-canal'
import { Route as AuthenticatedMoldeCodigoRouteImport } from './routes/_authenticated/molde.$codigo'
import { Route as AuthenticatedAdminVistaPreviaRouteImport } from './routes/_authenticated/admin.vista-previa'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPermisosRouteImport } from './routes/_authenticated/admin.permisos'
import { Route as AuthenticatedAdminPanelRouteImport } from './routes/_authenticated/admin.panel'
import { Route as AuthenticatedAdminDefectosRouteImport } from './routes/_authenticated/admin.defectos'
import { Route as AuthenticatedAdminColoresRouteImport } from './routes/_authenticated/admin.colores'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReparacionesRoute =
  AuthenticatedReparacionesRouteImport.update({
    id: '/reparaciones',
    path: '/reparaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecomendacionesBloqueoRoute =
  AuthenticatedRecomendacionesBloqueoRouteImport.update({
    id: '/recomendaciones-bloqueo',
    path: '/recomendaciones-bloqueo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreviewRoute = AuthenticatedPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPicarOfRoute = AuthenticatedPicarOfRouteImport.update({
  id: '/picar-of',
  path: '/picar-of',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfFabricadasRoute =
  AuthenticatedOfFabricadasRouteImport.update({
    id: '/of-fabricadas',
    path: '/of-fabricadas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMoldesRoute = AuthenticatedMoldesRouteImport.update({
  id: '/moldes',
  path: '/moldes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidenciasProductoRoute =
  AuthenticatedIncidenciasProductoRouteImport.update({
    id: '/incidencias-producto',
    path: '/incidencias-producto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidenciasRoute =
  AuthenticatedIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidenciaProductoFormRoute =
  AuthenticatedIncidenciaProductoFormRouteImport.update({
    id: '/incidencia-producto-form',
    path: '/incidencia-producto-form',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestionMoldesRoute =
  AuthenticatedGestionMoldesRouteImport.update({
    id: '/gestion-moldes',
    path: '/gestion-moldes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBloquearCanalRoute =
  AuthenticatedBloquearCanalRouteImport.update({
    id: '/bloquear-canal',
    path: '/bloquear-canal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMoldeCodigoRoute =
  AuthenticatedMoldeCodigoRouteImport.update({
    id: '/molde/$codigo',
    path: '/molde/$codigo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVistaPreviaRoute =
  AuthenticatedAdminVistaPreviaRouteImport.update({
    id: '/admin/vista-previa',
    path: '/admin/vista-previa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermisosRoute =
  AuthenticatedAdminPermisosRouteImport.update({
    id: '/admin/permisos',
    path: '/admin/permisos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPanelRoute = AuthenticatedAdminPanelRouteImport.update({
  id: '/admin/panel',
  path: '/admin/panel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDefectosRoute =
  AuthenticatedAdminDefectosRouteImport.update({
    id: '/admin/defectos',
    path: '/admin/defectos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminColoresRoute =
  AuthenticatedAdminColoresRouteImport.update({
    id: '/admin/colores',
    path: '/admin/colores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bloquear-canal': typeof AuthenticatedBloquearCanalRoute
  '/gestion-moldes': typeof AuthenticatedGestionMoldesRoute
  '/incidencia-producto-form': typeof AuthenticatedIncidenciaProductoFormRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/incidencias-producto': typeof AuthenticatedIncidenciasProductoRoute
  '/moldes': typeof AuthenticatedMoldesRoute
  '/of-fabricadas': typeof AuthenticatedOfFabricadasRoute
  '/picar-of': typeof AuthenticatedPicarOfRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/recomendaciones-bloqueo': typeof AuthenticatedRecomendacionesBloqueoRoute
  '/reparaciones': typeof AuthenticatedReparacionesRoute
  '/admin/colores': typeof AuthenticatedAdminColoresRoute
  '/admin/defectos': typeof AuthenticatedAdminDefectosRoute
  '/admin/panel': typeof AuthenticatedAdminPanelRoute
  '/admin/permisos': typeof AuthenticatedAdminPermisosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vista-previa': typeof AuthenticatedAdminVistaPreviaRoute
  '/molde/$codigo': typeof AuthenticatedMoldeCodigoRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bloquear-canal': typeof AuthenticatedBloquearCanalRoute
  '/gestion-moldes': typeof AuthenticatedGestionMoldesRoute
  '/incidencia-producto-form': typeof AuthenticatedIncidenciaProductoFormRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/incidencias-producto': typeof AuthenticatedIncidenciasProductoRoute
  '/moldes': typeof AuthenticatedMoldesRoute
  '/of-fabricadas': typeof AuthenticatedOfFabricadasRoute
  '/picar-of': typeof AuthenticatedPicarOfRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/recomendaciones-bloqueo': typeof AuthenticatedRecomendacionesBloqueoRoute
  '/reparaciones': typeof AuthenticatedReparacionesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/colores': typeof AuthenticatedAdminColoresRoute
  '/admin/defectos': typeof AuthenticatedAdminDefectosRoute
  '/admin/panel': typeof AuthenticatedAdminPanelRoute
  '/admin/permisos': typeof AuthenticatedAdminPermisosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vista-previa': typeof AuthenticatedAdminVistaPreviaRoute
  '/molde/$codigo': typeof AuthenticatedMoldeCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/bloquear-canal': typeof AuthenticatedBloquearCanalRoute
  '/_authenticated/gestion-moldes': typeof AuthenticatedGestionMoldesRoute
  '/_authenticated/incidencia-producto-form': typeof AuthenticatedIncidenciaProductoFormRoute
  '/_authenticated/incidencias': typeof AuthenticatedIncidenciasRoute
  '/_authenticated/incidencias-producto': typeof AuthenticatedIncidenciasProductoRoute
  '/_authenticated/moldes': typeof AuthenticatedMoldesRoute
  '/_authenticated/of-fabricadas': typeof AuthenticatedOfFabricadasRoute
  '/_authenticated/picar-of': typeof AuthenticatedPicarOfRoute
  '/_authenticated/preview': typeof AuthenticatedPreviewRoute
  '/_authenticated/recomendaciones-bloqueo': typeof AuthenticatedRecomendacionesBloqueoRoute
  '/_authenticated/reparaciones': typeof AuthenticatedReparacionesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/colores': typeof AuthenticatedAdminColoresRoute
  '/_authenticated/admin/defectos': typeof AuthenticatedAdminDefectosRoute
  '/_authenticated/admin/panel': typeof AuthenticatedAdminPanelRoute
  '/_authenticated/admin/permisos': typeof AuthenticatedAdminPermisosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vista-previa': typeof AuthenticatedAdminVistaPreviaRoute
  '/_authenticated/molde/$codigo': typeof AuthenticatedMoldeCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/bloquear-canal'
    | '/gestion-moldes'
    | '/incidencia-producto-form'
    | '/incidencias'
    | '/incidencias-producto'
    | '/moldes'
    | '/of-fabricadas'
    | '/picar-of'
    | '/preview'
    | '/recomendaciones-bloqueo'
    | '/reparaciones'
    | '/admin/colores'
    | '/admin/defectos'
    | '/admin/panel'
    | '/admin/permisos'
    | '/admin/usuarios'
    | '/admin/vista-previa'
    | '/molde/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/bloquear-canal'
    | '/gestion-moldes'
    | '/incidencia-producto-form'
    | '/incidencias'
    | '/incidencias-producto'
    | '/moldes'
    | '/of-fabricadas'
    | '/picar-of'
    | '/preview'
    | '/recomendaciones-bloqueo'
    | '/reparaciones'
    | '/'
    | '/admin/colores'
    | '/admin/defectos'
    | '/admin/panel'
    | '/admin/permisos'
    | '/admin/usuarios'
    | '/admin/vista-previa'
    | '/molde/$codigo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/bloquear-canal'
    | '/_authenticated/gestion-moldes'
    | '/_authenticated/incidencia-producto-form'
    | '/_authenticated/incidencias'
    | '/_authenticated/incidencias-producto'
    | '/_authenticated/moldes'
    | '/_authenticated/of-fabricadas'
    | '/_authenticated/picar-of'
    | '/_authenticated/preview'
    | '/_authenticated/recomendaciones-bloqueo'
    | '/_authenticated/reparaciones'
    | '/_authenticated/'
    | '/_authenticated/admin/colores'
    | '/_authenticated/admin/defectos'
    | '/_authenticated/admin/panel'
    | '/_authenticated/admin/permisos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vista-previa'
    | '/_authenticated/molde/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reparaciones': {
      id: '/_authenticated/reparaciones'
      path: '/reparaciones'
      fullPath: '/reparaciones'
      preLoaderRoute: typeof AuthenticatedReparacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recomendaciones-bloqueo': {
      id: '/_authenticated/recomendaciones-bloqueo'
      path: '/recomendaciones-bloqueo'
      fullPath: '/recomendaciones-bloqueo'
      preLoaderRoute: typeof AuthenticatedRecomendacionesBloqueoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preview': {
      id: '/_authenticated/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthenticatedPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/picar-of': {
      id: '/_authenticated/picar-of'
      path: '/picar-of'
      fullPath: '/picar-of'
      preLoaderRoute: typeof AuthenticatedPicarOfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/of-fabricadas': {
      id: '/_authenticated/of-fabricadas'
      path: '/of-fabricadas'
      fullPath: '/of-fabricadas'
      preLoaderRoute: typeof AuthenticatedOfFabricadasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moldes': {
      id: '/_authenticated/moldes'
      path: '/moldes'
      fullPath: '/moldes'
      preLoaderRoute: typeof AuthenticatedMoldesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidencias-producto': {
      id: '/_authenticated/incidencias-producto'
      path: '/incidencias-producto'
      fullPath: '/incidencias-producto'
      preLoaderRoute: typeof AuthenticatedIncidenciasProductoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidencias': {
      id: '/_authenticated/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof AuthenticatedIncidenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidencia-producto-form': {
      id: '/_authenticated/incidencia-producto-form'
      path: '/incidencia-producto-form'
      fullPath: '/incidencia-producto-form'
      preLoaderRoute: typeof AuthenticatedIncidenciaProductoFormRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestion-moldes': {
      id: '/_authenticated/gestion-moldes'
      path: '/gestion-moldes'
      fullPath: '/gestion-moldes'
      preLoaderRoute: typeof AuthenticatedGestionMoldesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bloquear-canal': {
      id: '/_authenticated/bloquear-canal'
      path: '/bloquear-canal'
      fullPath: '/bloquear-canal'
      preLoaderRoute: typeof AuthenticatedBloquearCanalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/molde/$codigo': {
      id: '/_authenticated/molde/$codigo'
      path: '/molde/$codigo'
      fullPath: '/molde/$codigo'
      preLoaderRoute: typeof AuthenticatedMoldeCodigoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vista-previa': {
      id: '/_authenticated/admin/vista-previa'
      path: '/admin/vista-previa'
      fullPath: '/admin/vista-previa'
      preLoaderRoute: typeof AuthenticatedAdminVistaPreviaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permisos': {
      id: '/_authenticated/admin/permisos'
      path: '/admin/permisos'
      fullPath: '/admin/permisos'
      preLoaderRoute: typeof AuthenticatedAdminPermisosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/panel': {
      id: '/_authenticated/admin/panel'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AuthenticatedAdminPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/defectos': {
      id: '/_authenticated/admin/defectos'
      path: '/admin/defectos'
      fullPath: '/admin/defectos'
      preLoaderRoute: typeof AuthenticatedAdminDefectosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/colores': {
      id: '/_authenticated/admin/colores'
      path: '/admin/colores'
      fullPath: '/admin/colores'
      preLoaderRoute: typeof AuthenticatedAdminColoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBloquearCanalRoute: typeof AuthenticatedBloquearCanalRoute
  AuthenticatedGestionMoldesRoute: typeof AuthenticatedGestionMoldesRoute
  AuthenticatedIncidenciaProductoFormRoute: typeof AuthenticatedIncidenciaProductoFormRoute
  AuthenticatedIncidenciasRoute: typeof AuthenticatedIncidenciasRoute
  AuthenticatedIncidenciasProductoRoute: typeof AuthenticatedIncidenciasProductoRoute
  AuthenticatedMoldesRoute: typeof AuthenticatedMoldesRoute
  AuthenticatedOfFabricadasRoute: typeof AuthenticatedOfFabricadasRoute
  AuthenticatedPicarOfRoute: typeof AuthenticatedPicarOfRoute
  AuthenticatedPreviewRoute: typeof AuthenticatedPreviewRoute
  AuthenticatedRecomendacionesBloqueoRoute: typeof AuthenticatedRecomendacionesBloqueoRoute
  AuthenticatedReparacionesRoute: typeof AuthenticatedReparacionesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminColoresRoute: typeof AuthenticatedAdminColoresRoute
  AuthenticatedAdminDefectosRoute: typeof AuthenticatedAdminDefectosRoute
  AuthenticatedAdminPanelRoute: typeof AuthenticatedAdminPanelRoute
  AuthenticatedAdminPermisosRoute: typeof AuthenticatedAdminPermisosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVistaPreviaRoute: typeof AuthenticatedAdminVistaPreviaRoute
  AuthenticatedMoldeCodigoRoute: typeof AuthenticatedMoldeCodigoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBloquearCanalRoute: AuthenticatedBloquearCanalRoute,
  AuthenticatedGestionMoldesRoute: AuthenticatedGestionMoldesRoute,
  AuthenticatedIncidenciaProductoFormRoute:
    AuthenticatedIncidenciaProductoFormRoute,
  AuthenticatedIncidenciasRoute: AuthenticatedIncidenciasRoute,
  AuthenticatedIncidenciasProductoRoute: AuthenticatedIncidenciasProductoRoute,
  AuthenticatedMoldesRoute: AuthenticatedMoldesRoute,
  AuthenticatedOfFabricadasRoute: AuthenticatedOfFabricadasRoute,
  AuthenticatedPicarOfRoute: AuthenticatedPicarOfRoute,
  AuthenticatedPreviewRoute: AuthenticatedPreviewRoute,
  AuthenticatedRecomendacionesBloqueoRoute:
    AuthenticatedRecomendacionesBloqueoRoute,
  AuthenticatedReparacionesRoute: AuthenticatedReparacionesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminColoresRoute: AuthenticatedAdminColoresRoute,
  AuthenticatedAdminDefectosRoute: AuthenticatedAdminDefectosRoute,
  AuthenticatedAdminPanelRoute: AuthenticatedAdminPanelRoute,
  AuthenticatedAdminPermisosRoute: AuthenticatedAdminPermisosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVistaPreviaRoute: AuthenticatedAdminVistaPreviaRoute,
  AuthenticatedMoldeCodigoRoute: AuthenticatedMoldeCodigoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
