ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS puede_ver_moldes BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS puede_ver_historial BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS puede_crear_incidencias BOOLEAN NOT NULL DEFAULT true;